Gorev_Yoneticisi/Models/YapilanIsler.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Gorev_Yoneticisi.Models
{
    public class YapilanIsler
    {
        public int Id { get; set; }
        public string Aciklama { get; set; }
        public string DetayliPlanlama { get; set; }
        public bool Durum { get; set; }
        public virtual ApplicationUser User { get; set; }
    }
}

Gorev_Yoneticisi/Controllers/YapilanIslersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Gorev_Yoneticisi.Models;
using Microsoft.AspNet.Identity;

namespace Gorev_Yoneticisi.Controllers
{
    public class YapilanIslersController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: YapilanIslers
        //[Authorize] FilterConfig içerisine ekledim.
        public ActionResult Index()
        {
            return View();
        }
        private IEnumerable<YapilanIsler> GetYapilanIslers()
        {
            string currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Id == currentUserId);
            IEnumerable<YapilanIsler> yapilanIslers = db.YapilanIslers.ToList().Where(x => x.User == currentUser);
            int bitenisler = 0;
            foreach(YapilanIsler yapilan in yapilanIslers)
            {
                if(yapilan.Durum)
                { 
                bitenisler++;
                }
            }
            ViewBag.Percent = Math.Round(100f * ((float)bitenisler / (float) yapilanIslers.Count()));
            return yapilanIslers;
        }
        public ActionResult DerleYapilanisTable()
        {
            return PartialView("_Yapilanistable",GetYapilanIslers());
        }
        // GET: YapilanIslers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            YapilanIsler yapilanIsler = db.YapilanIslers.Find(id);
            if (yapilanIsler == null)
            {
                return HttpNotFound();
            }
            return View(yapilanIsler);
        }

        // GET: YapilanIslers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: YapilanIslers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Aciklama,DetayliPlanlama,Durum")] YapilanIsler yapilanIsler)
        {
            if (ModelState.IsValid)
            {
                string currentUserId = User.Identity.GetUserId();
                ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Id == currentUserId);
                yapilanIsler.User = currentUser;

                db.YapilanIslers.Add(yapilanIsler);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(yapilanIsler);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AJAXCreate([Bind(Include = "Id,Aciklama,DetayliPlanlama")] YapilanIsler yapilanIsler)
        {
            if (ModelState.IsValid)
            {
                string currentUserId = User.Identity.GetUserId();
                ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Id == currentUserId);
                yapilanIsler.User = currentUser;
                yapilanIsler.Durum = false;
                db.YapilanIslers.Add(yapilanIsler);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return PartialView("_Yapilanistable", GetYapilanIslers());
        }
        // GET: YapilanIslers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            YapilanIsler yapilanIsler = db.YapilanIslers.Find(id);
            if (yapilanIsler == null)
            {
                return HttpNotFound();
            }
            string currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Id == currentUserId);
            if(yapilanIsler.User != currentUser)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            return View(yapilanIsler);
        }

        // POST: YapilanIslers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Aciklama,DetayliPlanlama,Durum")] YapilanIsler yapilanIsler)
        {
            if (ModelState.IsValid)
            {
                db.Entry(yapilanIsler).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(yapilanIsler);
        }
        [HttpPost]
        public ActionResult AJAXEdit(int? id, bool value)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            YapilanIsler yapilanIsler = db.YapilanIslers.Find(id);
            if (yapilanIsler == null)
            {
                return HttpNotFound();
            }
            else
            {
                yapilanIsler.Durum = value;
                db.Entry(yapilanIsler).State = EntityState.Modified;
                db.SaveChanges();
                return PartialView("_Yapilanistable", GetYapilanIslers());
            }
            
        }
        // GET: YapilanIslers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            YapilanIsler yapilanIsler = db.YapilanIslers.Find(id);
            if (yapilanIsler == null)
            {
                return HttpNotFound();
            }
            return View(yapilanIsler);
        }

        // POST: YapilanIslers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            YapilanIsler yapilanIsler = db.YapilanIslers.Find(id);
            db.YapilanIslers.Remove(yapilanIsler);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Gorev_Yoneticisi/Views/YapilanIslers/Create.cshtml
@model Gorev_Yoneticisi.Models.YapilanIsler

@{
    ViewBag.Title = "Plan Oluştur";
}

<h2>Plan Oluştur</h2>
<style>
    select, option {
        width: 280px;
        height: 40px;
    }

    option {
        overflow: hidden;
        white-space: nowrap;
        text-overflow: ellipsis;
    }
</style>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Plan Oluştur</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Aciklama, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Aciklama, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Aciklama, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DetayliPlanlama, "Detaylı Planlama", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.DetayliPlanlama, new SelectList(
              new List<Object>{
                   new { value = "Günlük" , text = "Günlük"  },
                   new { value = "Haftalık" , text = "Haftalık" },
                   new { value = "Aylık" , text = "Aylık" },
                },
              "value",
              "text",
               1))

            @Html.ValidationMessageFor(model => model.DetayliPlanlama, "", new { @class = "text-danger" })
        </div>
    </div> 
    <!--<div class="form-group">
        2@Html.LabelFor(model => model.DetayliPlanlama, htmlAttributes: new { 2@class = "control-label col-md-2" })
        <div class="col-md-10">
           2@Html.EditorFor(model => model.DetayliPlanlama, new { htmlAttributes = new { 2@class = "form-control" } })
            1@Html.ValidationMessageFor(model => model.DetayliPlanlama, "", new { 2@class = "text-danger" })
        </div>
    </div> -->

    <div class="form-group">
        @Html.LabelFor(model => model.Durum, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            <div class="checkbox">
                @Html.EditorFor(model => model.Durum)
                @Html.ValidationMessageFor(model => model.Durum, "", new { @class = "text-danger" })
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Oluştur" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Listeye Geri Dön", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Gorev_Yoneticisi/Views/YapilanIslers/Delete.cshtml
@model Gorev_Yoneticisi.Models.YapilanIsler

@{
    ViewBag.Title = "Plan Sil";
}

<h2>Plan Sil</h2>

<h3>Bu planı Silmek istediğinize emin misiniz?</h3>
<div>
    <h4>Plan Sil</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Aciklama)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Aciklama)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DetayliPlanlama)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DetayliPlanlama)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Durum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Durum)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-default" /> |
            @Html.ActionLink("Listeye Geri Dön", "Index")
        </div>
    }
</div>

Gorev_Yoneticisi/Views/YapilanIslers/Details.cshtml
@model Gorev_Yoneticisi.Models.YapilanIsler

@{
    ViewBag.Title = "Plan Detayları";
}

<h2>Plan Detayları</h2>

<div>
    <h4>Plan Detayları</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Aciklama)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Aciklama)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DetayliPlanlama)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DetayliPlanlama)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Durum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Durum)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Düzenle", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Listeye Geri Dön", "Index")
</p>

Gorev_Yoneticisi/Views/YapilanIslers/Edit.cshtml
@model Gorev_Yoneticisi.Models.YapilanIsler

@{
    ViewBag.Title = "Düzenle";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Plan Düzenle</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Aciklama, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Aciklama, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Aciklama, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DetayliPlanlama, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DetayliPlanlama, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DetayliPlanlama, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Durum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Durum)
                    @Html.ValidationMessageFor(model => model.Durum, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Listeye Geri Dön", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Gorev_Yoneticisi/Views/YapilanIslers/Index.cshtml
@model Gorev_Yoneticisi.Models.YapilanIsler

@{
    ViewBag.Title = "Yapılacaklar Listesi";
}
<style>
    select, option {
        width: 280px;
        height: 40px;
    }

    option {
        overflow: hidden;
        white-space: nowrap;
        text-overflow: ellipsis;
    }
</style>
<p>
    @Html.ActionLink("Yeni Plan Oluştur", "Create")
</p>
<h2>Yapılacak İşlerin Planlanması
</h2>
<div id="tableDiv">

</div>
<br />
<br />
<h2>Kısayol Plan oluştur</h2>
<div id="PlanOlustur">
    @using (Ajax.BeginForm("AJAXCreate", "YapilanIslers", new AjaxOptions
    {
        InsertionMode = InsertionMode.Replace,
        HttpMethod = "POST",
        UpdateTargetId = "tableDiv"
    }))
    {
        <div class="form-group">
            @Html.AntiForgeryToken()
            @Html.LabelFor(model => model.Aciklama, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Aciklama, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Aciklama, "", new { @class = "text-danger" })
            </div>
        </div>
        <br />
        <br />
        <div class="form-group">
            @Html.LabelFor(model => model.DetayliPlanlama, "Detaylı Planlama", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.DetayliPlanlama, new SelectList(
                  new List<Object>{
                       new { value = "Günlük" , text = "Günlük"  },
                       new { value = "Haftalık" , text = "Haftalık" },
                       new { value = "Aylık" , text = "Aylık" },
                    },
                  "value",
                  "text",
                   1))

                @Html.ValidationMessageFor(model => model.DetayliPlanlama, "", new { @class = "text-danger" })
            </div>
        </div>
    }
</div>
@section Scripts {
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script src="~/Custom_Scripts/DerleYapilanisTable.js"></script>
    @Scripts.Render("~/bundles/jqueryval")
    }

Gorev_Yoneticisi/Views/YapilanIslers/_Yapilanistable.cshtml
@model IEnumerable<Gorev_Yoneticisi.Models.YapilanIsler>

<div id="ProgressBarPlan">
    <div class="progress">
        <div class="progress-bar" role="progressbar"
             style="width:@(Html.AttributeEncode(ViewBag.Percent))%"></div>
    </div>
    <p>@(ViewBag.Percent)%</p>
</div>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Aciklama)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DetayliPlanlama)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Durum)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @if (!item.Durum)
                {
                    @Html.DisplayFor(modelItem => item.Aciklama)
                }
                else
                {
                <div class="BitenPlan">
                    @Html.DisplayFor(modelItem => item.Aciklama)
                </div>
                }
            </td>
            <td>
                @if (!item.Durum)
                {
                    @Html.DisplayFor(modelItem => item.DetayliPlanlama)
                }
                else
                {
                <div class="BitenPlan">
                    @Html.DisplayFor(modelItem => item.DetayliPlanlama)
                </div>
                }
            </td>
            <td>
                @Html.CheckBoxFor(modelItem => item.Durum, new { id=item.Id, @class = "DurumKontrol" })
            </td>
            <td>
                @Html.ActionLink("Düzenle", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Detay", "Details", new { id = item.Id }) |
                @Html.ActionLink("Sil", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>
<script src="~/Custom_Scripts/AddCheckBoxListener.js"></script>